### PR TITLE
Fix compile with 5.00

### PR DESCRIPTION
**Pull request by nojb**
Following ocaml/ocaml#10867

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @rgrinberg

**Comment by gasche** [comment]
@rgrinberg if I do the work of reviewing and merging this, are you okay to do the release? You did it last time.

(While we are at it, what about a Mustache release? :-))

**Comment by kit-ty-kate** [comment]
cc @gasche

**Comment by kit-ty-kate** [comment]
last call for release? (I’m on leave next month so I won’t be there to ping people)

**Pull request merged**
